[metadata]
name = pulpcore
version = 3.13.0.dev
description = Pulp Django Application and Related Modules
long_description = long_description
long_description_content_type = text/markdown
license = GPLv2+
license_file = LICENSE
author = Pulp Team
author_email = pulp-list@redhat.com
url = https://pulpproject.org
classifiers =
    License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
    Operating System :: POSIX :: Linux
    Development Status :: 5 - Production/Stable
    Framework :: Django
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7

[options]
python_requires = >=3.6
packages = find:
include_package_data = True
setup_requires =
    setuptools >= 40.8.0
    wheel >= 0.29.0
scripts =
    bin/pulp_content

[options.extras_require]
s3 =
    django-storages[boto3]
azure =
    django-storages[azure]
prometheus =
    django-prometheus

[options.entry_points]
console_scripts =
    pulpcore-manager = pulpcore.app.manage:manage
    pulpcore-worker = pulpcore.tasking.entrypoint:worker
